// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class ProductWarrantyReport
    {
        [Key]
        [Column("productid")]
        [StringLength(10)]
        [Unicode(false)]
        public string Productid { get; set; }
        [Key]
        [Column("warrantyid")]
        [StringLength(10)]
        [Unicode(false)]
        public string Warrantyid { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? AmountofDamageProduct { get; set; }

        [ForeignKey("Productid")]
        [InverseProperty("ProductWarrantyReport")]
        public virtual Product Product { get; set; }
        [ForeignKey("Warrantyid")]
        [InverseProperty("ProductWarrantyReport")]
        public virtual WarrantyReport Warranty { get; set; }
    }
}